name: .NET MAUI

on:
  push:
    branches:
      - "main"
  
jobs:
  
  Build:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
       platform: [macos-13, ubuntu-latest, macos-latest , windows-latest, ubuntu-22.04 ]
       dotnet: ["3.1.426",  '10.0.100-preview.5.25277.114' , "5.0.x", "6.0.x",  "7.0.x" , "8.0.x", "9.0.x", "10.0.x" ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET  ${{ matrix.dotnet }} SDK
        id: setup-dotnet
        uses: priyagupta108/setup-dotnet@update-install-scripts
        with:
          dotnet-version: ${{ matrix.dotnet }}

     
