name: .NET MAUI

on:
  push:
    branches:
      - "main"
  

jobs:
  
  Build_iOS:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
       platform: [macos-13, ubuntu-latest, macos-latest , windows-latest, ubuntu-22.04 ]
       dotnet: ["3.0.x",  "4.0.x" , "5.0.x", "6.0.x",  "7.0.x" , "8.0.x", "9.0.x", "10.0.x" ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 10.0.x SDK
        id: setup-dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Install .NET MAUI Workload
        run: |
          dotnet workload install maui 
      - name: Restore NuGet
        run: |
          dotnet restore ./src
      - name: Install Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build iOS App
        run: |
          dotnet build ./src -f net8.0-ios
        
