name: .NET MAUI

on:
  push:
    branches:
      - "main"
  
jobs:
  
  Build:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
       platform: [macos-13, ubuntu-latest, macos-latest , windows-latest, ubuntu-22.04, ubuntu-24.04-arm, windows-11-arm, ubuntu-22.04-arm ]
       dotnet: ["3.1", '3.0', '3.0.x', '3.1.x', '10.0.100-preview.5.25277.114' , '10.0', "10.0.x" , '10']
       exclude:
          - platform: windows-11-arm
            dotnet: '3.0'
          - platform: windows-11-arm
            dotnet: '3.0.x'
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET  ${{ matrix.dotnet }} SDK
        id: setup-dotnet
        uses: setup-actions-demo/setup-dotnet@eol-versions-removing
        with:
          dotnet-version: ${{ matrix.dotnet }}

     
