name: test-latest-channel-A.B-quality

on:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest, windows-11-arm, macos-15-intel, ubuntu-24.04-arm]
        quality: [preview, daily, ga]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6

      - name: Setup dotnet latest 8.0 with quality
        id: setup
        uses: mahabaleshwars/setup-dotnet@feature/497-dotnet-version-latest-keyword
        with:
          dotnet-version: latest
          dotnet-channel: '8.0'
          dotnet-quality: ${{ matrix.quality }}

      - name: Verify version
        shell: bash
        run: |
          dotnet --version
          dotnet --info
          echo "resolved=${{ steps.setup.outputs.dotnet-version }}"