name: Test Invalid SDK Format

on: push

jobs:
  test-partial:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Write global.json
        shell: bash
        run: |
          echo '{"sdk":{"version":"10","rollForward":"latestFeature"}}' > global.json
    

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Check version
        run: dotnet --version

  test-two-part:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Write global.json
        shell: bash
        run: |
          echo '{"sdk":{"version":"10.0","rollForward":"latestFeature"}}' > global.json
    

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Check version
        run: dotnet --version

  test-wildcard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Write global.json
        shell: bash
        run: |
            echo '{"sdk":{"version":"10.0.x","rollForward":"latestFeature"}}' > global.json
      

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Check version
        run: dotnet --version